"""Updated email column with index

Revision ID: 0ab067be6a0c
Revises: 8c30fccda7d9
Create Date: 2026-09-21 14:26:09.555580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab067be6a0c'
down_revision = '8c30fccda7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admins_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))
        batch_op.create_unique_constraint(batch_op.f('admins_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
