"""Added payment and receipt for attendee

Revision ID: 8c30fccda7d9
Revises: 887bea3449c3
Create Date: 2026-09-16 12:58:29.440330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c30fccda7d9'
down_revision = '887bea3449c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('receipt_url', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('receipt_url')
        batch_op.drop_column('amount_due')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
