"""altered attendees table to match current constraints

Revision ID: bae11940a8df
Revises: 7792a477bcae
Create Date: 2026-08-03 22:44:28.457713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae11940a8df'
down_revision = '7792a477bcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visitor', sa.Boolean(), nullable=False))
        batch_op.alter_column('faculty',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=3),
               nullable=True)
        batch_op.alter_column('qrcode',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('qrcode',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('faculty',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('is_visitor')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
